---
- name: Create Grafana directory
  file: 
    path: "{{ VAR_GRAFANA_DIR }}"
    recurse: yes
    state: directory
    owner: 472
    group: 472

- name: Start Grafana container
  docker_container:
    name: grafana 
    image: grafana/grafana:latest
    pull: yes
    state: started
    env:
       GF_SERVER_ROOT_URL: "{{ GF_SERVER_ROOT_URL }}"
       GF_SECURITY_ADMIN_PASSWORD: "{{ GF_SECURITY_ADMIN_PASSWORD }}"
       GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    labels:
      traefik.backend=grafana
      "traefik.frontend.rule=Host:{{ VAR_GRAFANA_URL }}"
      traefik.port=3000
      traefik.enable=true
    volumes:
    - "{{ VAR_GRAFANA_DIR }}:/var/lib/grafana:z"
    restart_policy: unless-stopped

